# Generated by Django 5.0.4 on 2024-04-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nameoffile_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameoffile',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
