# Generated by Django 5.0.4 on 2024-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_nameoffile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameoffile',
            name='file_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
