# Generated by Django 5.0.4 on 2024-04-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_nameoffile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameoffile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nameoffile',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
