# Generated by Django 5.0.4 on 2024-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_nameoffile_image_alter_nameoffile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameoffile',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
